### ISSUE TITLE
open gunshop trigger bug

### ISSUE THREAD

**Issue by FlockersDesign** [TTVErraticAlcoholic/gun_catalogue#2]
there is a bug in the resource that makes it that the open gunshop popup is always on no metter were you are 
this also makes it that you can not get on youre hores or anny interactions that request the E bind

thank you

**Comment by ErraticL** [comment]
Are you using the RedEM framework?
Are there any errors in your (server) console?
Did you rename the resource? 
It is VERY important that you do NOT rename the resource unless you know what you're doing.

**Comment by DerFloenz** [comment]
I have the same Problem, using RedEm Framework, no errors in Server Console or F8 Console and no renameing. Only Thing i found out is when i go to the Store trigger the "real" popup than leave the Store its gone away.

**Comment by ErraticL** [comment]
Looking into it.

**Comment by DerFloenz** [comment]
i still have the Problem, i think it is somthing with the Distance when i came into the 100 Distance Radius it closes the prompt and then its fine but when i rejoin the server out of the 100 Distance Radius it has the Prompt open. i tried a lot now with changing radius and the else function but nothing works.
