### ISSUE TITLE
Reloading Weapon

### ISSUE THREAD

**Issue by Reckless75** [TTVErraticAlcoholic/gun_catalogue#5]
**weapons wont reload after purchasing ammo for the weapon**

Was the resource renamed? = NO

Are there any errors in F8? If possible, provide a screenshot of your console. = NO

Are there any errors in your server console? If possible, provide a screenshot of your console. = NO

Are you using the RedEM framework? = YES

What exactly were you doing when you noticed the error/issue occur? = Just bought a gun with ammo

Are there any other resources that might conflict with gun_catalogue? = NO

**Comment by robwhitewick** [comment]
What version of the script are you using? If you are using the one with inventory support have you used the provided config?
