### ISSUE TITLE
cant use lantern

### ISSUE THREAD

**Issue by phantomora** [TTVErraticAlcoholic/gun_catalogue#6]
Was the resource renamed? No

Are there any errors in F8? If possible, provide a screenshot of your console. No

Are there any errors in your server console? If possible, provide a screenshot of your console. No

Are you using the RedEM framework? Yes

What exactly were you doing when you noticed the error/issue occur? I am able to buy the lantern but when i open my inventory and select it to use nothing happens. 
![Untitled](https://user-images.githubusercontent.com/11086012/89964216-93c8f280-dc17-11ea-928b-dc0440b3c275.jpg)

Are there any other resources that might conflict with gun_catalogue?No

**Comment by robwhitewick** [comment]
Are you sure you correctly inserted the provided config into the redem inventory?

**Comment by phantomora** [comment]
i copied everything from the inventory config.lua

**Comment by williamniels** [comment]
输入我的邀请码 Y6P6BH6 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum
