### ISSUE TITLE
Using Gun Catalogue with Inventory 2.0

### ISSUE THREAD

**Issue by worldofmadness** [TTVErraticAlcoholic/gun_catalogue#7]
Was the resource renamed? **NO**

Are there any errors in your server console? If possible, provide a screenshot of your console
[https://ihostimages.uk/images/2020/10/15/mstsc_7tnd7bAXSB.png]( https://ihostimages.uk/images/2020/10/15/mstsc_7tnd7bAXSB.png)

Are you using the RedEM framework? **YES**

What exactly were you doing when you noticed the error/issue occur? **trying to purchase a gun but those errors keep appearing and i am scratching my head as to why when looking at the code**

Are there any other resources that might conflict with gun_catalogue? **NO I know we are using Inventory 2.0 now so dont know if there is something causing it with that.**

**Comment by btwentyone** [comment]
Good evening,

If you haven't found the answer yet, here it is in two parts

https://github.com/TTVErraticAlcoholic/gun_catalogue/pulls
